name: Node.js CI

on:
  push

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v3
    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Run cypress tests
      run: npx cypress run --spec "cypress/e2e/isolation/*" --browser chrome --headed