name: Node.js CI

on:
  push:
    branches:
      - bury08

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]

    steps:
    - name: Git clone
      uses: actions/checkout@v3
    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install